config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs do
    get 'toggle_status', on: :member
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  include Placeholder
  has_many :technologies
  accepts_nested_attributes_for :technologies, reject_if: lambda { |attr| attr['name'].blank? }
  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.angular
    where(subtitle: :Angular)
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on Rails") }

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator('600', '400')
    self.thumb_image ||= Placeholder.image_generator('350', '200')
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout 'portfolio'
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :update, :create, :edit]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def ruby_on_rails
    @ruby_on_rails_items = Portfolio.ruby_on_rails_portfolio_items
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live'}
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end

  def show
    @portfolio_item =  Portfolio.find(params[:id])
  end

  def update
    @portfolio_item = Portfolio.find params[:id]
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio_item }
      else
        format.html { render :edit }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @portfolio_item = Portfolio.find(params[:id])
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully deleted'}
    end
  end

  private

    def portfolio_params
      params.require(:portfolio).permit(:title,
                                        :subtitle,
                                        :body,
                                        technologies_attributes: [:name]
                                      )
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio_item) do |f|  %>
    <div class="field">
      <%=  f.label :title %>
      <%=  f.text_field :title %>
    </div>
    <div class="field">
      <%=  f.label :body %>
      <%=  f.text_area :body %>
    </div>

    <ul>
      <%= f.fields_for :technologies do |technology_form| %>
          <li>
            <%= technology_form.label :name %>
            <%= technology_form.text_field :name %>
          </li>
      <% end %>
    </ul>

    <div class="actions">
      <%=  f.submit %>
    </div>

<% end  %>

app/views/portfolios/_portfolio_item.html.erb
<p><%=  portfolio_item.title  %></p>
<p><%=  portfolio_item.subtitle  %></p>
<p><%=  portfolio_item.body  %></p>
<%= image_tag  portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %></p> <br>
<%=  link_to "Show More Details...", portfolio_show_path(portfolio_item) %>
<% if logged_in?(:site_admin) %>
    <%=  link_to "Edit #{portfolio_item.title}", edit_portfolio_path(portfolio_item) %>
    <%=  link_to "Delete Portfolio Item", portfolio_path(portfolio_item), method: :delete, data: {confirm: 'Are you sure'} %>
<% end %>
<br><br>

app/views/portfolios/edit.html.erb
<h1>Edit Portfolio Item</h1>
<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>
<%= link_to "Create a New Portfolio", new_portfolio_path if logged_in?(:site_admin ) %>
<%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio Item</h1>
<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image %>
<h1><%= @portfolio_item.title  %></h1>
<em><%= @portfolio_item.subtitle %></em>
<p><%=	@portfolio_item.body %></p>
<h2>Technologies Used:</h2>
<% @portfolio_item.technologies.each do |t| %>
<p><%= t.name  %></p>
<% end  %>