config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs do
    get 'toggle_status', on: :member
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Would you like to work together?</h1>
<hr>
<div class="row">
  <div class="col-md-6">
    <h3>Office Address</h3>
    <p>
      Akintola Williams Deloitte House
      Olusoji Idowu St, Ilupeju, Lagos
    </p>
    <h3>Phone Number</h3>
    <p><%= number_to_phone "08062397763" %></p>
    <h3>Email</h3>
    <p><a href="mailto:koya@portfolio.com?subject=PortfolioContact">Email me</a></p>
  </div>

  <div class="col-md-6">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1193.910637981259!2d3.3662221407241266!3d6.553373051002323!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x103b8d91a9420db5%3A0xeb2698bd112b950!2sAkintola+Williams+Deloitte+House!5e0!3m2!1sen!2sng!4v1515367907032" width="450" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>
</div>

app/views/pages/home.html.erb
<main role="main" class="inner cover">
  <h1 class="cover-heading">Cover your page.</h1>
  <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
  <p class="lead">
    <%= link_to 'About Me', about_path, class: "btn btn-lg btn-secondary" %>
  </p>
</main>